### ISSUE TITLE
What should be done about SSLv3 'POODLE' attack?

### ISSUE THREAD

**Issue by jaredj** [smtpd/qpsmtpd#134]
[SSLv3 is no longer secure due to the 'POODLE' attack](https://blog.mozilla.org/security/2014/10/14/the-poodle-attack-and-the-end-of-ssl-3-0/)

What should QP do about this?  There are three obvious options:

a.  Disable SSLv3 in the TLS plugin.  The benefits:  no TLS transactions would ever use the insecure SSLv3, and fewer security auditors will pester QP administrators about this issue.

b.  Leave SSLv3 enabled in the TLS plugin.  The benefits:  when talking to clients that don't support the other cyphers we support, SSLv3 would allow for an insecure encrypted communication that is preferable to insecure plaintext communication.

c.  Make supported cyphers configurable in the TLS plugin (presumably the SSL_version string).  I think there was a previous discussion on this which concluded that this wasn't necessary.  I'm not sure whether this issue really does anything to change that conclusion.

Our fork has gone with A, mainly because we get calls from customers all the time about audit failures like this and the easiest thing is to avoid the audit failures, and to be able to tell inquisitive customers that we've disabled SSLv3 in everything that uses encryption.  So if we were ever to merge back the upstream TLS plugin (which would not be difficult at all aside from this issue), it would require upstream to have done A or C, or else for us to change our minds and choose B.

**Comment by salvis** [comment]
I expected to be able to disable SSLv3 by setting config/tls_ciphers to
HIGH:!SSLv2:!SSLv3
However, this gives me
TLS failed: Could not create SSL socket:  at /home/smtpd/qpsmtpd/plugins/tls line 187, <STDIN> line 2.
and blocks sending mail.

**Comment by msimerson** [comment]
Resolved in PR #192

**Comment by jaredj** [comment]
@salvis - ssl_ciphers isn't the same thing as ssl_version.  ssl_version is what you want and it's not exposed by any configuration directives.  what you want is to apply the patch from #192

**Comment by salvis** [comment]
Thanks for the comment and patch!
