### ISSUE TITLE
inconsistent log formatting

### ISSUE THREAD

**Issue by jaredj** [smtpd/qpsmtpd#182]
#175 attempted to add some information about which plugin is running to log entries, but it was reverted because it was actually redundant.  I wanted to merge [the bit of Qpsmtpd::varlog() that did this](https://github.com/smtpd/qpsmtpd/blob/master/lib/Qpsmtpd.pm#L132-L136) to our fork, but it turns out it's already in there.  However, it's only executed if no logging plugin is enabled so that varlog() has to output directly to STDERR.  [Most](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/adaptive#L47-L56) [logging](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/apache#L60-L71) [plugins](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/warn#L68-L72) [do](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/transaction_id#L34-L45) add the plugin name and hook name to the log entry, however two common logging plugins, [logging/file](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/file#L287-L288) and [logging/syslog](https://github.com/smtpd/qpsmtpd/blob/master/plugins/logging/syslog#L184), do not.

Why don't we just decide on a standard format (presumably the format already used most places), and do the prepending in Qpsmtpd::varlog() instead of leaving it up to each logging plugin?

**Comment by msimerson** [comment]
+1
