### ISSUE TITLE
dkim plugin: Sign for others

### ISSUE THREAD

**Issue by salvis** [smtpd/qpsmtpd#208]
I'm still wrestling with dkim...

The doc says

> **Sign for others**
> 
> Following the directions above will configure QP to DKIM sign messages from authenticated senders of example.org. Suppose you host client.com and would like to DKIM sign their messages too? Do that as follows:
> 
>  cd ~smtpd/config/dkim
>  ln -s example.org client.com
>
> QP will follow the symlink target and sign client.com emails with the example.org DKIM key.

I've done that, but I keep getting the signature for example.org (i.e. d=example.org), which means it fails alignment with user@client.com.

How can I get d=client.com if the sender is user@client.com?

Hans

**Comment by msimerson** [comment]
I wrote the per-domain DKIM signing before DMARC. Back then, the most common use of the DKIM signing module was an ISP that signed all the mail they relayed with their own DKIM key. By signing it with their own d=provider.com domain, they didn't need to publish the DKIM public key in every domains DNS zone.

With the advent of DMARC applying alignment checks agains the DKIM signature, your use case will become the new "normal," and before long it won't make any sense for a provide to sign anything that doesn't bear their domain name in the From header. 

The solution is easy: create a new DKIM key for each domain you want to sign for. Then publish the DKIM public key in that zones DNS. 

The way the DKIM plugin works is that if config/dkim is a symlink, then the d= property is the symlink target name.

**Comment by salvis** [comment]
Now it works like a charm, thank you!

In my case, client.com is my domain, too, and it doesn't make much sense to have different keys, but I didn't realize that dkim was so smart to differentiate between following the symlink and having a real directory.

The documentation seemed to suggest that you could configure DMARC to get the unaligned DKIM to pass, but I don't think this is true. I've posted a pull request with a doc update.

Hans

**Comment by msimerson** [comment]
Well, you **can** just use a single key for many domains. The thing is, you **must** publish that same key in each domains DNS. **If** you've done that, then just create additional *directories* in config/dkim for each domain and hard link the DKIM key into it. Example:

````
cd ~smtpd/config/dkim
mkdir client1.com client2.com client3.com
ln provider.com/selector provider.com/private client1.com/
ln provider.com/selector provider.com/private client2.com/
ln provider.com/selector provider.com/private client3.com/
````

Now all three client domains share the same selector and private signing key, and you've published the same public key in the DNS for all 4 domains.
