### ISSUE TITLE
Plugin sender_permitted_from ignores whitelisthelo

### ISSUE THREAD

**Issue by salvis** [smtpd/qpsmtpd#226]
Today I have to argue the other way around...

sender_permitted_from calls is_immune(), but is_immune() checks only *whitelisthost* and *whitelistsender*.

I send some mail through SpamCop and back, and when the mail comes back, it's blocked by SPF. I'd like to fix this by whitelisting SpamCop's HELO, rather than relying on guessing the IPs of their MTAs.

The whitelist plugin does evaluate *whitelisthelo* and set a transaction note, but no one is checking that note. Is that a design choice or a bug?

**Comment by msimerson** [comment]
You realize it's trivially easy for someone to impersonal at the HELO hostname? And thus whitelisting on data that can't be authenticated in any way (unlike say, a hostname using FCrDNS or a MAIL FROM  using SPF) is likely a very bad idea indeed? You can do this in your own copies of the plugins but it's not a sensible thing for QP to do by default.

**Comment by salvis** [comment]
Yes, of course. But they would have to guess the whitelisted HELO hostname first. That can work for a pretty long time, maybe even indefinitely.

The two supported lists both don't work so well: hard-coding IP addresses in *whitelisthosts* is not so great because IP addresses can change easily, and *whitelistsenders* doesn't work because this is not dependent on specific senders.

But I have no problem accepting your judgement -- thanks for considering it.

(I'm still wrestling with managing the three repos and I think I've messed up my GitHub fork...)
