### ISSUE TITLE
Port issue for TLS on port 465

### ISSUE THREAD

**Issue by morungos** [smtpd/qpsmtpd#239]
I think there might be an incorrect port setting in the `plugin/tls`, which is breaking when deploying on port 465. This port should start clear, and then provide STARTTLS to switch on SSL, same as port 25. However, the code for connecting reads:

```
if ( ! defined $local_port || $local_port != 465 ) {  # SMTPS
```

This should probably read:

```
if ( ! defined $local_port || $local_port != 587 ) {  # SMTPS
```

Using 465 here makes the server start in SSL directly, which is not the normal port 465 behaviour. Where a server on 587 should start directly in SSL. The use of negated conditions makes it harder to read the logic here, but basically 465 is not SMTPS, it's the legacy/secondary SMTP. 

I'll happy send a pull request if needed.

**Comment by msimerson** [comment]
I think you don't understand what SMTPS is. Please see [wikipedia](http://en.wikipedia.org/wiki/SMTPS).

**Comment by morungos** [comment]
I think you shouldn't necessarily assume what people know, but I take your point. In practice the external email system I was using to test (and ultimately proxy to) had 465 set to behave as an alternate 25, helpfully.

**Comment by msimerson** [comment]
I didn't assume anything. You state that port 465 "should start clear" when that is most certainly not the case. That's why I provided links to help upgrade your knowledge.

**Comment by morungos** [comment]
And the link did help, although I already was very well aware of both reference sources and the function of starttls, having just spent several hours debugging at that level on (what turned out to be) and wrongly configured server at my hosting service.
