### ISSUE TITLE
Add option to hide leakage of user info through Auth-Res and Received from header

### ISSUE THREAD

**Issue by analogic** [smtpd/qpsmtpd#240]
There should be option to not add Authentication-Results header for outgoing email since it reveals **username** and **login method**. Received header shows **remote user IP** address and sometimes show **local network IP address** (plugin Helo with header X-HELO also). 

I am going to write privacy plugin to remove/update these headers, but it should be hidden by default i guess.

**Comment by analogic** [comment]
Sorry, the issue https://github.com/smtpd/qpsmtpd/issues/194 mention this

**Comment by analogic** [comment]
Simple privacy enhancing plugin http://poste.io/qpsmtpd/remove-headers

**Comment by msimerson** [comment]
This is a reasonable way to handle it locally. If this plugin had POD and was configurable so users could modify the list of headers to **clean**, I'd encourage you to submit it as a PR that closes #194.
