### ISSUE TITLE
GMail rejects to connect over SMTP

### ISSUE THREAD

**Issue by julianxhokaxhiu** [smtpd/qpsmtpd#274]
Hi,

I'm actually using qpsmtpd on my server setup, to handle my emails and I'm pretty much satisfied with it. Although I'm facing one difficulty that is not allowing me to use my personal GMail account with my mail server, by allowing google to connect through SMTP to my mail server.

This is my list of currently used plugins:
```
## can lead to dos if we reject some proper connections based on karma!
karma reject 0 db_dir /data/karma

tls
hosts_allow
fcrdns
quit_fortune
earlytalker
count_unrecognized_commands 4
relay
#whitelist
dnsbl reject 1 reject_type disconnect
rhsbl
helo policy strict reject 0
auth/auth_dovecot
dont_require_anglebrackets
badmailfrom reject naughty
resolvable_fromhost reject 1
sender_permitted_from reject 1
rcpt_database
badrcptto
rcpt_ok
dovecot_quota
#headers reject 0 reject_type temp require From future 2 past 15
bogus_bounce log
bounce_stamp
dkim reject 0
dmarc reporting 0
attachments ".ADE,.ADP,.BAT,.CHM,.CMD,.COM,.CPL,.EXE,.HTA,.INS,.ISP,.JAR,.JSE,.LIB,.LNK,.MDE,.MSC,.MSP,.MST,.PIF,.SCR,.SCT,.SHB,.SYS,.VB,.VBE,.VBS,.VXD,.WSC,.WSF,.WSH,.JS"
spamassassin reject 12 munge_subject_threshold 6 subject_prefix *****SPAM*****
virus/clamdscan clamd_socket /var/run/clamav/clamd.ctl
naughty reject data
queue/extended_qmail
remove_headers
#spamassassin_relay reject 10 headers none
```

This is the log when trying to use `465 over SSL`:
```
2016-10-16 14:48:40 [karma] - pass, no record
2016-10-16 14:48:40 [tls] - pass, connect via SMTPS
2016-10-16 14:48:40 [fcrdns] - karma 1 (1)
2016-10-16 14:48:40 [fcrdns] - pass
2016-10-16 14:48:41 [earlytalker] - pass, not spontaneous
2016-10-16 14:48:41 [relay] - skip, no match
2016-10-16 14:48:41 - 220 mail.julianxhokaxhiu.com ESMTP
2016-10-16 14:48:41 - dispatching EHLO mail-lf0-f41.google.com
2016-10-16 14:48:41 [helo] - karma 1 (2)
2016-10-16 14:48:41 [helo] - pass
2016-10-16 14:48:41 - 250-mail.julianxhokaxhiu.com Hi mail-lf0-f41.google.com [209.85.215.41]
2016-10-16 14:48:41 - 250-PIPELINING
2016-10-16 14:48:41 - 250-8BITMIME
2016-10-16 14:48:41 - 250 AUTH PLAIN LOGIN
2016-10-16 14:48:41 - dispatching AUTH PLAIN <hidden credentials>
```

This is the log when trying to use `587 over TLS`
```
2016-10-16 14:30:22 [karma] - pass, no record
2016-10-16 14:30:22 [fcrdns] - karma 1 (1)
2016-10-16 14:30:22 [fcrdns] - pass
2016-10-16 14:30:23 [earlytalker] - pass, not spontaneous
2016-10-16 14:30:23 [relay] - skip, no match
2016-10-16 14:30:23 - 220 mail.julianxhokaxhiu.com ESMTP
2016-10-16 14:30:23 - dispatching EHLO mail-lf0-f47.google.com
2016-10-16 14:30:23 [helo] - karma 1 (2)
2016-10-16 14:30:23 [helo] - pass
2016-10-16 14:30:23 - 250-mail.julianxhokaxhiu.com Hi mail-lf0-f47.google.com [209.85.215.47]
2016-10-16 14:30:23 - 250-PIPELINING
2016-10-16 14:30:23 - 250-8BITMIME
2016-10-16 14:30:23 - 250 STARTTLS
2016-10-16 14:30:23 - dispatching STARTTLS
2016-10-16 14:30:23 - 220 Go ahead with TLS
2016-10-16 14:30:23 [tls] - TLS setup returning
2016-10-16 14:30:23 - dispatching EHLO mail-lf0-f47.google.com
2016-10-16 14:30:23 [helo] - karma 1 (3)
2016-10-16 14:30:23 [helo] - pass
2016-10-16 14:30:23 - 250-mail.julianxhokaxhiu.com Hi mail-lf0-f47.google.com [209.85.215.47]
2016-10-16 14:30:23 - 250-PIPELINING
2016-10-16 14:30:23 - 250-8BITMIME
2016-10-16 14:30:23 - 250 AUTH PLAIN LOGIN
2016-10-16 14:30:23 - dispatching AUTH PLAIN <hidden credentials>
```

Can somebody help me to understand what I am doing wrong? Using Thunderbird anyway works fine.
Feel free to ask for more configuration files if needed.

Thanks in advance,
Julian

**Comment by charliebrady** [comment]
Your grammar is not perfect when you say "GMail rejects to connect over 
SMTP" so I do not understand what you are trying to say.

You haven't provided any evidence to show that gmail cannot connect to 
your server, so I do not know what advice I can give you.

Please be clear about what you think is a problem. What happened which you 
did not expect to happen, or what did not happen which you expected to 
happen?

How were you causing gmail to connect to your server? What does your 
server have to do with your personal gmail account?

**Comment by julianxhokaxhiu** [comment]
Hi @charliebrady

Despite of my "grammar issues" the title is pretty much self explaining. As you may know inside of Gmail private accouts, inside the settings, you can add an SMTP account, if you would like to sent emails from another domain by not treating it as an alias.

Therefore, into that mask I'm adding my own mail server domain where the ports are listening and, whenever Gmail try to add the account, it fails by always saying "Authentication issue. Code SENT_SECOND_EHLO" or similar output.

Credentials are working fine since I'm using actually a Web Interface, where I am currently sending emails from, but I would like to integrate it to my personal Gmail account.

Would be helpful if anybody can share a protip. Any log I could provide is attached. If you need further configuration files, feel free to ask.

Best regards,
Julian

**Comment by holck** [comment]
I am no expert in qpsmtpd, but I'm also sorry to say that I don't quite 
understand your problem.

Do you want email from Gmail to go through you own email server? So that 
when someone sends an email to your Gmail-account, it is forwarded to an 
account on your own server? Gmail should be able to do that without any 
credentials.

Please explain your problem in more detail. What exactly do you want to 
achieve? How do you know that there is a problem?

Kind regards,

Jesper Holck

**Comment by julianxhokaxhiu** [comment]
Dear @holck let me explain with an explicit screenshot what I am trying to do.

First of all, the feature of GMail I am referring to, is this one:
https://support.google.com/mail/answer/22370?hl=en

This is actually the screenshot with the error printed, `587 via TLS`:
![587viatls](https://cloud.githubusercontent.com/assets/1237070/19496100/54f366b6-9586-11e6-9fe9-9639290653af.png)

while this is the answer using `465 via SSL`:
![465viassl](https://cloud.githubusercontent.com/assets/1237070/19496111/5ff0d6b6-9586-11e6-8576-5aff7b4489ce.png)

As you see, both of them are giving the same error, which is:
```
Authentication failed. Please check your username/password.
[Server response: Missed upload deadline (9.99s) (state SENT_SECOND_EHLO) code(0) ]
```

May this come by any Plugin configured in a wrong way? Some months ago I was having a setup with Dovecot and I never had any issue with this.

Any help is still really appreciated.

Best regards,
Julian

**Comment by tyskjohan** [comment]
Hi

If you Google "Missed upload deadline" it seems like this is a Gmail error message that also happens with Office365 for unknown reasons, and the remedy is "keep trying". 

J

**Comment by holck** [comment]
I will recommend you to check the contents of /var/log/qpsmtpd/current 
and /var/log/sqpsmtpd/current. Here, you should be able to find log 
entries for the failed authentication attempts from Gmail. If you can't 
find these entries, you probably need to open the relevant port external 
SMTP access to your server.

I will also recommend that you in the Server Manager, E-mail settings, 
check that your SMTP is open for authenticated access.

Good luck!

Jesper

**Comment by jaredj** [comment]
Sounds like banner delay needs to be disabled or to exclude gmail's servers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by julianxhokaxhiu** [comment]
Hi @jaredj may I know which file can I check related to this? So i can test and give some proper feedback.

Thank you in advance :)

**Comment by charliebrady** [comment]
On Sun, 16 Oct 2016, Julian Xhokaxhiu wrote:

> This is my list of currently used plugins:
> ...
> earlytalker
> ...

Try removing that one, just to see if it makes a difference.

> This is the log when trying to use `465 over SSL`:
> ```
> 2016-10-16 14:48:40 [karma] - pass, no record
> 2016-10-16 14:48:40 [tls] - pass, connect via SMTPS
> 2016-10-16 14:48:40 [fcrdns] - karma 1 (1)
> 2016-10-16 14:48:40 [fcrdns] - pass
> 2016-10-16 14:48:41 [earlytalker] - pass, not spontaneous
> 2016-10-16 14:48:41 [relay] - skip, no match
> 2016-10-16 14:48:41 - 220 mail.julianxhokaxhiu.com ESMTP
> 2016-10-16 14:48:41 - dispatching EHLO mail-lf0-f41.google.com
> 2016-10-16 14:48:41 [helo] - karma 1 (2)
> 2016-10-16 14:48:41 [helo] - pass
> 2016-10-16 14:48:41 - 250-mail.julianxhokaxhiu.com Hi mail-lf0-f41.google.com [209.85.215.41]
> 2016-10-16 14:48:41 - 250-PIPELINING
> 2016-10-16 14:48:41 - 250-8BITMIME
> 2016-10-16 14:48:41 - 250 AUTH PLAIN LOGIN
> 2016-10-16 14:48:41 - dispatching AUTH PLAIN <hidden credentials>
> ```

You truncated the log just when it was becoming interesting. What happens 
next?

**Comment by julianxhokaxhiu** [comment]
There is nothing next, and this is the issue. There are just the logs. As I see they say that everything is fine right? But still doesn't work.

Can you please point me which one should I disable?

**Comment by julianxhokaxhiu** [comment]
I tested without earlytalker plugin and nothing changes. Still the same.

Logs are full, nothing is truncated, that's the funny part of this story :\

**Comment by julianxhokaxhiu** [comment]
Issue found! Is totally unrelated to qpsmtpd, but to Dovecot Authorization! The GMail error is missleading, but it seems that the plugin that handles the authorization via Dovecot is not passing correctly some data to dovecot process.

I'm totally sure that once I fix this, everything else will work. And that's why there's no more log after `dispatching AUTH PLAIN` :D

Thank you very much for all the effort, your tips helped me to get here, Best regards!

**Comment by bartsiek** [comment]
Hi, I'm facing the same problems (using dovecot-2.0.9-22.el6.x86_64): GMail cannot authenticate the account - (user/pw etc are all correct)

> Issue found! Is totally unrelated to qpsmtpd, but to Dovecot Authorization! The GMail error is missleading, but it seems that the plugin that handles the authorization via Dovecot is not passing correctly some data to dovecot process.
> 
> I'm totally sure that once I fix this, everything else will work. And that's why there's no more log after `dispatching AUTH PLAIN` :D

As you mention the handling of authorization between Dovecot seems the issue here: are you willing to share the solution?
Thanks!

**Comment by julianxhokaxhiu** [comment]
@bartsiek I'd be more than happy to do so, but I don't even remember what I did. Although I can point you to this issue, maybe it will help you: https://bitbucket.org/analogic/mailserver/issues/72/smtp-not-working-with-gmail
