### ISSUE TITLE
How to set the config dir location for qpstmpd-forkserver

### ISSUE THREAD

**Issue by wwparker** [smtpd/qpsmtpd#279]
I installed qpsmtpd-0.93 on FreeBSD with pkg install p5-qpsmtpd
I have it running, but it doesn't seem to load my config. How do I get the qpsmtpd-forkserver to use a specific config directory? I'd like to load the directory localed at /usr/local/etc/qpsmtpd/config, but I can't find anyway to set or right the config file. The documentation on the Internet appears to be years out of date and even looking at the perl sources, I don't see how the documentation that I did find could work,

How to do I set the config dir?

**Comment by msimerson** [comment]
The only supported location for the config dir is ./config. If you want to put it somewhere else, drop a symlink to it with a target of ./config in the QP install dir.

**Comment by wwparker** [comment]
Thank you for the answer. 
Looks like I'll just make a private clone as I don't want to that. I don't want to do that sort of stuff anymore.

**Comment by wwparker** [comment]
For future reference of anyone that looks at this issue, the answer is 

export QPSMTPD_CONFIG="/usr/local/etc/qpsmtpd/config"

Don't know why this had to require so much work.
