### ISSUE TITLE
Request for port 587 + TLS documentation pointer

### ISSUE THREAD

**Issue by davidfavor** [smtpd/qpsmtpd#280]
Looking for documentation for running...

1) port 25 no auth

2) port 587 + TLS

Pointers appreciated. Thanks.

**Comment by msimerson** [comment]
[authentication](https://github.com/smtpd/qpsmtpd/blob/master/docs/authentication.md) and [tls](https://github.com/smtpd/qpsmtpd/blob/master/plugins/tls)

**Comment by davidfavor** [comment]
So in plugins/config, add...

tls
tls_before_auth

And run server as...

qpsmtpd-forkserver --port 25 --port 587

**Comment by davidfavor** [comment]
Yep... That did the trick...

Thanks.
