### ISSUE TITLE
plugins/ident/geoip should first try v2

### ISSUE THREAD

**Issue by unnilennium** [smtpd/qpsmtpd#289]
V2 database are more accurate and are the only updated from now. While it could be good to keep support for v1, the presence of a v1 db should not prevent the use of most accurate db just because both are available to allow backward compatibility for other software.

here a change I suggest:
```
--- geoip.ori	2019-01-05 14:08:42.066334179 -0500
+++ geoip	2019-01-05 14:09:39.366888335 -0500
@@ -145,8 +145,8 @@
 
 sub load_geoip {
     my ( $self ) = @_;
-    $self->load_geoip1() and return 1;
-    $self->load_geoip2() and return 1;
+	$self->load_geoip2() and return 1;
+	$self->load_geoip1() and return 1;
     return 0;
 }

```

**Comment by msimerson** [comment]
Agreed. A PR updating this is welcome.
