### ISSUE TITLE
plugins/ident/geoip  fails with geoip1 

### ISSUE THREAD

**Issue by unnilennium** [smtpd/qpsmtpd#290]
having only geoip v1 available on a server I end up with this error 

@400000005c303f97033075ac 8675 check_badcountries: could not load GeoIP2
@400000005c303f9a11a0d71c 8675 (connect) earlytalker: pass, not spontaneous
@400000005c303f9a11a17f14 8675 (connect) relay: skip, no match
@400000005c303f9a11af6994 8675 FATAL PLUGIN ERROR [check_badcountries]:  Can't locate object method "name_by_addr" via package "Geo::IP" at /usr/share/qpsmtpd/plugins/check_badcountries line 433.
@400000005c303f9a186dc6cc 8675 (connect) dnsbl: pass

perl-Geo-IP-1.38-6.el6.x86_64
this method was introduced with  perl-Geo-IP-1.39 and deprecates org_by_addr. While you could say just update, it could be easy to at least add a line to prevent the error : 

```
--- geoip.ori	2019-01-05 14:08:42.066334179 -0500
+++ geoip	2019-01-05 14:27:40.356208925 -0500
@@ -429,6 +429,7 @@
         return $self->set_asn_ipv6($ip);
     }
     return if ! $self->{GeoIPASNum};
+    return if ! $self->{GeoIPASNum}->can('name_by_addr');
 
     my $asn = $self->{GeoIPASNum}->name_by_addr($ip) or return;
     if ('AS' eq substr($asn, 0, 2)) {
```

This would be the very least to allow the plugin to work, we could also try the method org_by_addr and use it if available.

**Comment by msimerson** [comment]
PR is welcome. Reviewing the PR is the most work I'm willing to contribute to GeoIP v1
