### ISSUE TITLE
Racially orientated naming

### ISSUE THREAD

**Issue by reetp** [smtpd/qpsmtpd#292]
Would the developers please consider renaming some of the terminology to be less racially 'charged'.

Items such as black list/white list etc should be reconsidered.

Thank you.

**Comment by msimerson** [comment]
TL;DR: No
---
If you're serious, you have some work ahead of you.

1. read the etymology of the term blacklist and grasp that getting blacklisted had nothing to do with the color of the blacklisted persons skin.
2. prove your assertion that the term is racially charged.
3. visit your favorite thesaurus and find some suggestions that are suitable replacements for the terms.
4. Submit a PR.

**Comment by reetp** [comment]
Amazing that so many

**Comment by reetp** [comment]
Amazing that so many things do get left like a PR of mine a while back, but this was answered immediately.

Note I am not saying whether they are or are not racist terms. Note I am not accusing anyone of bring racist.

Throwing dictionaries & thesauruses around does not fix a situation. They don't cover perception.

1 & 2. I am not black and not really fit to judge if they're offensive terms or not, though personally I have long considered them ill judged. To err on the side of caution does no harm. 

3. Allow/Block or Permit/Deny or similar. I'm sure it isn't difficult to conjure up a few. Plenty of others are doing so as we speak.

4. See my opening comment. If I actually thought a PR might be considered I'd look at it, but both my previous effort, and your extremely blunt response, doesn't incline me to believe that you will.

**Comment by msimerson** [comment]
1. notice the level of maintenance of this package. Mosts users and developers have long since moved on. Set your expectations accordingly.
2. if you want changes, contribute them.

**Comment by abh** [comment]
Hi John,

I am not active in this project anymore (and not since many years ago), but I am curious if you have any suggestions or pointers to similar work elsewhere?

In related domains we (very broad “we as an industry”...) have figured out to replace master/slave with {controller,manager} and {device,client,worker} or similar at least in most new work in the last decade or so.

Ask

**Comment by dani** [comment]
Well, except that everyone still talks about master/slave (and blacklist/whitelist). I just can't understand how this can offend anyone. We're talking about softwares and lists of servers. How on earth could someone think this has anything to do with races ? That's above my head, really.

**Comment by reetp** [comment]
I'm white so I'm not really in a position to judge, and I'm not entirely sure any other white person is either.

Clearly some think it is an issue, and particularly in the current climate I think perhaps it is something that should be considered.

Ironically this article was published a couple of days after I had actually initially raised the point elsewhere. It has a lots of examples where organisations are making efforts to remove potentially offensive wordage, and that includes removing Master/Slave as well.

https://www.theregister.com/2020/06/08/developers_renew_push_to_get/

It actually can't do any harm to change - yes, I get the inconvenience. However, it would actually be more indicative of the operations concerned.

Personally I think that 'Permit/Allow' and 'Deny/Block' are much more descriptive than 'White' and 'Black', especially where 'White' is considered 'good' and 'Black' is considered 'bad'.

**Comment by reetp** [comment]
Follow up. Spamassassin 4.0

"All rules, functions, command line options and modules that contain "whitelist" or "blacklist" have been renamed to "welcomelist" and "blocklist" terms"

https://lwn.net/Articles/918145/
