### ISSUE TITLE
v0.96 seems to ignore config/me + config/timeout

### ISSUE THREAD

**Issue by davidfavor** [smtpd/qpsmtpd#302]
It appears this code has somehow died, as neither of these %defaults lib/Qpsmtpd/Config.pm is honored any longer.

At least... best I recall... setting these use to work...

**Comment by unnilennium** [comment]
config/smtpgreeting

**Comment by davidfavor** [comment]
Thanks!

**Comment by wornet-aer** [comment]
Since this was somehow a config question, the issue can be closed now.
