### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kjetilk** [smtpd/qpsmtpd#305]
I just had a look at the commit log, and it does seem to me to be a sufficient number of useful stuff there to warrant a release?

**Comment by msimerson** [comment]
I would merge such a PR.

**Comment by kjetilk** [comment]
I may have a little time on my hands now. What would need to be added to get a release done?

**Comment by msimerson** [comment]
It's been so long, and I likely cut the last release, and I honestly don't remember. I'd go back and look at the last release, see what was done in the PR, and then do the same. In Haraka, I created [a wiki page](https://github.com/haraka/Haraka/wiki/Release-Process) that documents the steps for a release. It would be good to do that here as well.
