### ISSUE TITLE
Add plugin to accept a specially-formatted recipient and subsequently execute a pre-configured command on the server (such as to SSH to the connecting IP)

### ISSUE THREAD

**Issue by flimzy** [smtpd/qpsmtpd#59]

**Comment by biergaizi** [comment]
What is your purpose to make a SMTP server works like CGI scripts or [Webmin](https://github.com/webmin/webmin) control panels?

**Comment by jaredj** [comment]
This issue was mainly created to remind us to contribute our own plugin that we have written to do this.  Our own application is to allow us to execute a "call home" feature that opens up an ssh port that we can use to securely connect to our remote SAAS appliances running QP.

**Comment by msimerson** [comment]
Closing open feature requests, as there's nobody to implement them.
