### ISSUE TITLE
Work around buggy Outlook quoted-printable output

### ISSUE THREAD

**Issue by flimzy** [smtpd/qpsmtpd#65]
Outlook is buggy and occasionally and generates quoted-printable output which does not specify whether lines should be terminated with \r\n or \n when in fact they ought to be terminated with \r\n.  Given this input, MIME::Tools assumes \n, breaking some files.  This plugin attempts to identify attachments affected by this Outlook issue; if we find any, we want to transmit the original (broken) encoding rather than re-encoding with bad assumptions.

This matters whenever the message is re-written in such a way that the MIME message data is altered (such as when adding a signature).

**Comment by msimerson** [comment]
Closing open feature requests, as there's nobody to implement them.
